# Generated by Django 3.0.5 on 2020-04-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
