# Generated by Django 3.0.5 on 2020-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_chambre_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='image',
            field=models.ImageField(upload_to='media/pics'),
        ),
    ]
