# Generated by Django 3.0.5 on 2020-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
