# Generated by Django 3.0.5 on 2020-04-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_chambre_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
