# Generated by Django 3.0.5 on 2020-05-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('avis', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
