# Generated by Django 3.0.5 on 2020-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField(default=0)),
                ('Email', models.EmailField(max_length=40)),
                ('Date_Check_In', models.DateField()),
                ('Date_Check_Out', models.DateField()),
                ('Adulte', models.IntegerField(default=0)),
                ('Children', models.IntegerField(default=0)),
                ('Note', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chambre',
            name='image',
            field=models.ImageField(upload_to='media/pics'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='media/pics'),
        ),
    ]
