# Generated by Django 5.0.6 on 2024-06-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_reservation_adulte_alter_reservation_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
